#pragma once
enum FsmList
{
	fsmSEQ = 0,
	fsmInPick,
	fsmFoamRail,
	fsmTrayShuttle,
	fsmFoamSendElev,
	fsmFoamRecvElev,
	fsmFoamPartialElev,
	fsmFoamConv,
	fsmFoamPk,
	fsmFoamLtCst,
	fsmFoamRtCst,
	fsmMbbShuttle,
	fsmMbbQc,
	fsmBtmFoldConv,
	fsmFoldPk,
	fsmLtLabelFeeder,
	fsmRtLabelFeeder,
	fsmLabelLaser,
	fsmLtLabelShuttle,
	fsmRtLabelShuttle,
	fsmMbbLtCst,
	fsmMbbRtCst,
	fsmLtCobot,
	fsmRtCobot,
	fsmMAX,
};