#pragma once

// VACUUM PART
enum VacuumIndexMainAir
{
	MAIN_AIR_CHECK = 0,
	MAIN_AIR_MAX,
};

enum PosOfvcMbbOpenBtm
{
	MBB_OPEN_BTM_ON = 0,
	MBB_OPEN_BTM_OFF,
	MBB_OPEN_BTM_MAX,
};

enum PosOfvcMbbOpenTop
{
	MBB_OPEN_TOP_ON = 0,
	MBB_OPEN_TOP_OFF,
	MBB_OPEN_TOP_MAX,
};

enum PosOfvcMbbOpenTop2
{
	MBB_OPEN_TOP2_ON = 0,
	MBB_OPEN_TOP2_OFF,
	MBB_OPEN_TOP2_MAX,
};

enum PosOfvcSealNozzle
{
	SEAL_NOZZLE_ON = 0,
	SEAL_NOZZLE_OFF,
	SEAL_NOZZLE_MAX,
};

enum PosOfvcSealNozzleN2
{
	SEAL_NOZZLE_N2_ON = 0,
	SEAL_NOZZLE_N2_OFF,
	SEAL_NOZZLE_N2_MAX,
};

enum PosOfvcLoadCellFt
{
	LOADCELL_FT_ON = 0,
	LOADCELL_FT_OFF,
	LOADCELL_FT_MAX,
};

enum PosOfvcLoadCellRr
{
	LOADCELL_RR_ON = 0,
	LOADCELL_RR_OFF,
	LOADCELL_RR_MAX,
};

enum PosOfvcLtCobotLabel
{
	LT_COBOT_LABEL_ON = 0,
	LT_COBOT_LABEL_OFF,
	LT_COBOT_LABEL_MAX,
};

enum PosOfvcLtCobotFoam
{
	LT_COBOT_FOAM_ON = 0,
	LT_COBOT_FOAM_OFF,
	LT_COBOT_FOAM_MAX,
};

enum PosOfvcLtCobotFoam2
{
	LT_COBOT_FOAM2_ON = 0,
	LT_COBOT_FOAM2_OFF,
	LT_COBOT_FOAM2_MAX,
};

enum PosOfvcFoamPkLaser
{
	FOAM_LASER_ON = 0,
	FOAM_LASER_OFF,
	FOAM_LASER_MAX,
};

enum PosOfvcFoamFlip
{
	FOAM_FLIP_ON = 0,
	FOAM_FLIP_OFF,
	FOAM_FLIP_MAX,
};

enum PosOfvcFoamFlip2
{
	FOAM_FLIP2_ON = 0,
	FOAM_FLIP2_OFF,
	FOAM_FLIP2_MAX,
};

enum PosOfvcFoamPk
{
	FOAM_PK_ON = 0,
	FOAM_PK_OFF,
	FOAM_PK_MAX,
};

enum PosOfvcFoamPk2
{
	FOAM_PK2_ON = 0,
	FOAM_PK2_OFF,
	FOAM_PK2_MAX,
};

enum PosOfvcFlowLabelExhaust
{
	FLOW_LABEL_EXHAUST_ON = 0,
	FLOW_LABEL_EXHAUST_OFF,
	FLOW_LABEL_EXHAUST_MAX,
};

enum PosOfvcQcSealedHead
{
	QC_SEALED_HEAD_ON = 0,
	QC_SEALED_HEAD_OFF,
	QC_SEALED_HEAD_MAX,
};

enum PosOfvcLtLabelRecv
{
	LT_LABEL_RECV_ON = 0,
	LT_LABEL_RECV_OFF,
	LT_LABEL_RECV_MAX,
};

enum PosOfvcRtLabelRecv
{
	RT_LABEL_RECV_ON = 0,
	RT_LABEL_RECV_OFF,
	RT_LABEL_RECV_MAX,
};

enum PosOfvcRtCobotLabel
{
	RT_COBOT_LABEL_ON = 0,
	RT_COBOT_LABEL_OFF,
	RT_COBOT_LABEL_MAX,
};

enum PosOfvcRtCobotMbb
{
	RT_COBOT_MBB_ON = 0,
	RT_COBOT_MBB_OFF,
	RT_COBOT_MBB_MAX,
};

enum PosOfvcRtCobotMbb2
{
	RT_COBOT_MBB2_ON = 0,
	RT_COBOT_MBB2_OFF,
	RT_COBOT_MBB2_MAX,
};


// CYLINDER PART
enum PosOfCylInPkOc
{
	IN_PK_OPEN = 0,
	IN_PK_CLOSE,
	IN_PK_OC_MAX,
};

enum PosOfCylBtmFoamTableUd
{
	BTM_FOAM_TABLE_UP = 0,
	BTM_FOAM_TABLE_DN,
	BTM_FOAM_TABLE_UD_MAX,
};

enum PosOfCylBtmFoamStopUd
{
	BTM_FOAM_STOP_UP = 0,
	BTM_FOAM_STOP_DN,
	BTM_FOAM_STOP_UD_MAX,
};

enum PosOfCylBtmFoamFtClampOc
{
	BTM_FOAM_FT_CLAMP_OPEN = 0,
	BTM_FOAM_FT_CLAMP_CLOSE,
	BTM_FOAM_FT_CLAMP_OC_MAX,
};

enum PosOfCylBtmFoamRrClampOc
{
	BTM_FOAM_RR_CLAMP_OPEN = 0,
	BTM_FOAM_RR_CLAMP_CLOSE,
	BTM_FOAM_RR_CLAMP_OC_MAX,
};

enum PosOfCylTopFoamStopUd
{
	TOP_FOAM_STOP_UP = 0,
	TOP_FOAM_STOP_DN,
	TOP_FOAM_STOP_UD_MAX,
};

enum PosOfCylTrayShuttleNozzleUd
{
	TRAY_SHUTTLE_NOZZLE_UP = 0,
	TRAY_SHUTTLE_NOZZLE_DN,
	TRAY_SHUTTLE_NOZZLE_UD_MAX,
};

enum PosOfCylTrayShuttleBridgeUd
{
	TRAY_SHUTTLE_BRIDGE_UP = 0,
	TRAY_SHUTTLE_BRIDGE_DN,
	TRAY_SHUTTLE_BRIDGE_UD_MAX,
};

enum PosOfcylTrayShuttleBridgeFb
{
	TRAY_SHUTTLE_BRIDGE_FWD = 0,
	TRAY_SHUTTLE_BRIDGE_BWD,
	TRAY_SHUTTLE_BRIDGE_FB_MAX,
};

enum PosOfCylTrayShuttleFtStopFb
{
	TRAY_SHUTTLE_FT_STOP_FWD = 0,
	TRAY_SHUTTLE_FT_STOP_BWD,
	TRAY_SHUTTLE_FT_STOP_FB_MAX,
};

enum PosOfCylTrayShuttleRrStopFb
{
	TRAY_SHUTTLE_RR_STOP_FWD = 0,
	TRAY_SHUTTLE_RR_STOP_BWD,
	TRAY_SHUTTLE_RR_STOP_FB_MAX,
};

enum PosOfCylTrayShuttleFtMaskUd
{
	TRAY_SHUTTLE_FT_MASK_UP = 0,
	TRAY_SHUTTLE_FT_MASK_DN,
	TRAY_SHUTTLE_FT_MASK_UD_MAX,
};

enum PosOfCylTrayShuttleRrMaskUd
{
	TRAY_SHUTTLE_RR_MASK_UP = 0,
	TRAY_SHUTTLE_RR_MASK_DN,
	TRAY_SHUTTLE_RR_MASK_UD_MAX,
};

enum PosOfCylMbbOpenTopGuideFb
{
	MBB_OPEN_TOP_GUIDE_FWD = 0,
	MBB_OPEN_TOP_GUIDE_BWD,
	MBB_OPEN_TOP_GUIDE_FB_MAX,
};

enum PosOfCylMbbOpenTopVacUd
{
	MBB_OPEN_TOP_VAC_UP = 0,
	MBB_OPEN_TOP_VAC_DN,
	MBB_OPEN_TOP_VAC_UD_MAX,
};

enum PosOfCylMbbOpenTopClampUd
{
	MBB_OPEN_TOP_CLAMP_UP = 0,
	MBB_OPEN_TOP_CLAMP_DN,
	MBB_OPEN_TOP_CLAMP_UD_MAX,
};

enum PosOfCylSealNozzleFb
{
	SEAL_NOZZLE_FWD = 0,
	SEAL_NOZZLE_BWD,
	SEAL_NOZZLE_FB_MAX,
};

enum PosOfCylSealMbbOpenGuideFtOc
{
	SEAL_MBB_OPEN_GUIDE_FT_OPEN = 0,
	SEAL_MBB_OPEN_GUIDE_FT_CLOSE,
	SEAL_MBB_OPEN_GUIDE_FT_OC_MAX,
};

enum PosOfCylSealMbbOpenGuideRrOc
{
	SEAL_MBB_OPEN_GUIDE_RR_OPEN = 0,
	SEAL_MBB_OPEN_GUIDE_RR_CLOSE,
	SEAL_MBB_OPEN_GUIDE_RR_OC_MAX,
};

enum PosOfCylSealNozzleMfcOc
{
	SEAL_NOZZLE_MFC_OPEN = 0,
	SEAL_NOZZLE_MFC_CLOSE,
	SEAL_NOZZLE_MFC_OC_MAX,
};

enum PosOfCylSealBtmGuideUd
{
	SEAL_BTM_GUIDE_UP = 0,
	SEAL_BTM_GUIDE_DN,
	SEAL_BTM_GUIDE_UD_MAX,
};

enum PosOfCylSealerBtmUd
{
	SEALER_BTM_UP = 0,
	SEALER_BTM_DN,
	SEALER_BTM_UD_MAX,
};

enum PosOfCylSealerTopFtUd
{
	SEALER_TOP_FT_UP = 0,
	SEALER_TOP_FT_DN,
	SEALER_TOP_FT_UD_MAX,
};

enum PosOfCylSealerTopRrUd
{
	SEALER_TOP_RR_UP = 0,
	SEALER_TOP_RR_DN,
	SEALER_TOP_RR_UD_MAX,
};

enum PosOfCylSealTopGuideUd
{
	SEAL_TOP_GUIDE_UP = 0,
	SEAL_TOP_GUIDE_DN,
	SEAL_TOP_GUIDE_UD_MAX,
};

enum PosOfCylLtCobotLabelPkUd
{
	LT_COBOT_LABEL_PK_UP = 0,
	LT_COBOT_LABEL_PK_DN,
	LT_COBOT_LABEL_PK_UD_MAX,
};

enum PosOfCylLtCobotLabelPkTurnFb
{
	LT_COBOT_LABEL_PK_TURN_FWD = 0,
	LT_COBOT_LABEL_PK_TURN_BWD,
	LT_COBOT_LABEL_PK_TURN_FB_MAX,
};

enum PosOfCylFoamRecvElevLtAlignFb
{
	FOAM_RECV_ELEV_LT_ALIGN_FWD = 0,
	FOAM_RECV_ELEV_LT_ALIGN_BWD,
	FOAM_RECV_ELEV_LT_ALIGN_FB_MAX,
};

enum PosOfCylFoamRecvElevRrAlignFb
{
	FOAM_RECV_ELEV_RR_ALIGN_FWD = 0,
	FOAM_RECV_ELEV_RR_ALIGN_BWD,
	FOAM_RECV_ELEV_RR_ALIGN_FB_MAX,
};

enum PosOfCylFoamRecvElevLtStopFb
{
	FOAM_RECV_ELEV_LT_STOP_FWD = 0,
	FOAM_RECV_ELEV_LT_STOP_BWD,
	FOAM_RECV_ELEV_LT_STOP_FB_MAX,
};

enum PosOfCylFoamRecvElevRtStopFb
{
	FOAM_RECV_ELEV_RT_STOP_FWD = 0,
	FOAM_RECV_ELEV_RT_STOP_BWD,
	FOAM_RECV_ELEV_RT_STOP_FB_MAX,
};

enum PosOfCylFoamRrStackLiftUd
{
	FOAM_RR_STACK_LIFT_UP = 0,
	FOAM_RR_STACK_LIFT_DN,
	FOAM_RR_STACK_LIFT_UD_MAX,
};

enum PosOfCylFoamRrStackLtStopFb
{
	FOAM_RR_STACK_LT_STOP_FWD = 0,
	FOAM_RR_STACK_LT_STOP_BWD,
	FOAM_RR_STACK_LT_STOP_FB_MAX,
};

enum PosOfCylFoamRrStackRtStopFb
{
	FOAM_RR_STACK_RT_STOP_FWD = 0,
	FOAM_RR_STACK_RT_STOP_BWD,
	FOAM_RR_STACK_RT_STOP_FB_MAX,
};

enum PosOfCylFoamFtStackLiftUd
{
	FOAM_FT_STACK_LIFT_UP = 0,
	FOAM_FT_STACK_LIFT_DN,
	FOAM_FT_STACK_LIFT_UD_MAX,
};

enum PosOfCylFoamFtStackLtStopFb
{
	FOAM_FT_STACK_LT_STOP_FWD = 0,
	FOAM_FT_STACK_LT_STOP_BWD,
	FOAM_FT_STACK_LT_STOP_FB_MAX,
};

enum PosOfCylFoamFtStackRtStopFb
{
	FOAM_FT_STACK_RT_STOP_FWD = 0,
	FOAM_FT_STACK_RT_STOP_BWD,
	FOAM_FT_STACK_RT_STOP_FB_MAX,
};

enum PosOfCylFoamSendElevLtAlignFb
{
	FOAM_SEND_ELEV_LT_ALIGN_FWD = 0,
	FOAM_SEND_ELEV_LT_ALIGN_BWD,
	FOAM_SEND_ELEV_LT_ALIGN_FB_MAX,
};

enum PosOfCylFoamSendElevRtAlignFb
{
	FOAM_SEND_ELEV_RT_ALIGN_FWD = 0,
	FOAM_SEND_ELEV_RT_ALIGN_BWD,
	FOAM_SEND_ELEV_RT_ALIGN_FB_MAX,
};

enum PosOfCylFoamPartialElevLtAlignFb
{
	FOAM_PARTIAL_ELEV_LT_ALIGN_FWD = 0,
	FOAM_PARTIAL_ELEV_LT_ALIGN_BWD,
	FOAM_PARTIAL_ELEV_LT_ALIGN_FB_MAX,
};

enum PosOfCylFoamPartialElevRrAlignFb
{
	FOAM_PARTIAL_ELEV_FT_ALIGN_FWD = 0,
	FOAM_PARTIAL_ELEV_FT_ALIGN_BWD,
	FOAM_PARTIAL_ELEV_FT_ALIGN_FB_MAX,
};

enum PosOfCylMbbShuttleAlignFtFb
{
	MBB_SHUTTLE_ALIGN_FT_FWD = 0,
	MBB_SHUTTLE_ALIGN_FT_BWD,
	MBB_SHUTTLE_ALIGN_FT_FB_MAX,
};

enum PosOfCylMbbShuttleAlignRrFb
{
	MBB_SHUTTLE_ALIGN_RR_FWD = 0,
	MBB_SHUTTLE_ALIGN_RR_BWD,
	MBB_SHUTTLE_ALIGN_RR_FB_MAX,
};

enum PosOfCylMbbShuttleClampFtFb
{
	MBB_SHUTTLE_CLAMP_FT_FWD = 0,
	MBB_SHUTTLE_CLAMP_FT_BWD,
	MBB_SHUTTLE_CLAMP_FT_FB_MAX,
};

enum PosOfCylMbbShuttleClampRrFb
{
	MBB_SHUTTLE_CLAMP_RR_FWD = 0,
	MBB_SHUTTLE_CLAMP_RR_BWD,
	MBB_SHUTTLE_CLAMP_RR_FB_MAX,
};

enum PosOfCylQcSealedHeadBtmFtVacUd
{
	QC_SEALED_HEAD_BTM_FT_VAC_UP = 0,
	QC_SEALED_HEAD_BTM_FT_VAC_DN,
	QC_SEALED_HEAD_BTM_FT_VAC_UD_MAX,
};

enum PosOfCylQcSealedHeadBtmRrVacUd
{
	QC_SEALED_HEAD_BTM_RR_VAC_UP = 0,
	QC_SEALED_HEAD_BTM_RR_VAC_DN,
	QC_SEALED_HEAD_BTM_RR_VAC_UD_MAX,
};

enum PosOfCylQcSealedHeadTopFtClampUd
{
	QC_SEALED_HEAD_TOP_FT_CLAMP_UP = 0,
	QC_SEALED_HEAD_TOP_FT_CLAMP_DN,
	QC_SEALED_HEAD_TOP_FT_CLAMP_UD_MAX,
};

enum PosOfCylQcSealedHeadTopRrClampUd
{
	QC_SEALED_HEAD_TOP_RR_CLAMP_UP = 0,
	QC_SEALED_HEAD_TOP_RR_CLAMP_DN,
	QC_SEALED_HEAD_TOP_RR_CLAMP_UD_MAX,
};

enum PosOfCylQcSealedTrayStopUd
{
	QC_SEALED_TRAY_STOP_UP = 0,
	QC_SEALED_TRAY_STOP_DN,
	QC_SEALED_TRAY_STOP_UD_MAX,
};

enum PosOfCylQcSealedTrayAlignFtFb
{
	QC_SEALED_TRAY_ALIGN_FT_FWD = 0,
	QC_SEALED_TRAY_ALIGN_FT_BWD,
	QC_SEALED_TRAY_ALIGN_FT_FB_MAX,
};

enum PosOfCylQcSealedTrayAlignRrFb
{
	QC_SEALED_TRAY_ALIGN_RR_FWD = 0,
	QC_SEALED_TRAY_ALIGN_RR_BWD,
	QC_SEALED_TRAY_ALIGN_RR_FB_MAX,
};

enum PosOfCylMbbFoldAssistUd
{
	MBB_FOLD_ASSIST_UP = 0,
	MBB_FOLD_ASSIST_DN,
	MBB_FOLD_ASSIST_UD_MAX,
};

enum PosOfCylMbbFoldAlignFtFb
{
	MBB_FOLD_ALIGN_FT_FWD = 0,
	MBB_FOLD_ALIGN_FT_BWD,
	MBB_FOLD_ALIGN_FT_FB_MAX,
};

enum PosOfCylMbbFoldAlignRrFb
{
	MBB_FOLD_ALIGN_RR_FWD = 0,
	MBB_FOLD_ALIGN_RR_BWD,
	MBB_FOLD_ALIGN_RR_FB_MAX,
};

enum PosOfCylMbbFoldRtFb
{
	MBB_FOLD_RT_FWD = 0,
	MBB_FOLD_RT_BWD,
	MBB_FOLD_RT_FB_MAX,
};

enum PosOfCylMbbFoldRtFtOc
{
	MBB_FOLD_RT_FT_OPEN = 0,
	MBB_FOLD_RT_FT_CLOSE,
	MBB_FOLD_RT_FT_OC_MAX,
};

enum PosOfCylMbbFoldRtRrOc
{
	MBB_FOLD_RT_RR_OPEN = 0,
	MBB_FOLD_RT_RR_CLOSE,
	MBB_FOLD_RT_RR_OC_MAX,
};

enum PosOfCylMbbFoldPkLtBlockTurnFb
{
	MBB_FOLD_PK_LT_BLOCK_TURN_FWD = 0,
	MBB_FOLD_PK_LT_BLOCK_TURN_BWD,
	MBB_FOLD_PK_LT_BLOCK_TURN_FB_MAX,
};

enum PosOfCylMbbFoldPkLtBlockFtOc
{
	MBB_FOLD_PK_LT_BLOCK_FT_OPEN = 0,
	MBB_FOLD_PK_LT_BLOCK_FT_CLOSE,
	MBB_FOLD_PK_LT_BLOCK_FT_OC_MAX,
};

enum PosOfCylMbbFoldPkLtBlockRrOc
{
	MBB_FOLD_PK_LT_BLOCK_RR_OPEN = 0,
	MBB_FOLD_PK_LT_BLOCK_RR_CLOSE,
	MBB_FOLD_PK_LT_BLOCK_RR_OC_MAX,
};

enum PosOfCylMbbFoldPkClampOc
{
	MBB_FOLD_PK_CLAMP_OPEN = 0,
	MBB_FOLD_PK_CLAMP_CLOSE,
	MBB_FOLD_PK_CLAMP_OC_MAX,
};

enum PosOfCylLtLabelFeederFb
{
	LT_LABEL_FEEDER_FWD = 0,
	LT_LABEL_FEEDER_BWD,
	LT_LABEL_FEEDER_FB_MAX,
};

enum PosOfCylLtLabelFeederMountFb
{
	LT_LABEL_FEEDER_MOUNT_FWD = 0,
	LT_LABEL_FEEDER_MOUNT_BWD,
	LT_LABEL_FEEDER_MOUNT_FB_MAX,
};

enum PosOfCylLtLabelFeederLockFtFb
{
	LT_LABEL_FEEDER_LOCK_FT_FWD = 0,
	LT_LABEL_FEEDER_LOCK_FT_BWD,
	LT_LABEL_FEEDER_LOCK_FT_FB_MAX,
};

enum PosOfCylLtLabelFeederLockRrFb
{
	LT_LABEL_FEEDER_LOCK_RR_FWD = 0,
	LT_LABEL_FEEDER_LOCK_RR_BWD,
	LT_LABEL_FEEDER_LOCK_RR_FB_MAX,
};

enum PosOfCylLtLabelRecvUd
{
	LT_LABEL_RECV_UP = 0,
	LT_LABEL_RECV_DN,
	LT_LABEL_RECV_UD_MAX,
};

enum PosOfCylLtLabelRecvFb
{
	LT_LABEL_RECV_FWD = 0,
	LT_LABEL_RECV_BWD,
	LT_LABEL_RECV_FB_MAX,
};

enum PosOfCylLtLabelRecvEjectPinLtUd
{
	LT_LABEL_RECV_EJECT_PIN_LT_UP = 0,
	LT_LABEL_RECV_EJECT_PIN_LT_DN,
	LT_LABEL_RECV_EJECT_PIN_LT_UD_MAX,
};

enum PosOfCylLtLabelRecvEjectPinRtUd
{
	LT_LABEL_RECV_EJECT_PIN_RT_UP = 0,
	LT_LABEL_RECV_EJECT_PIN_RT_DN,
	LT_LABEL_RECV_EJECT_PIN_RT_UD_MAX,
};

enum PosOfCylRtLabelFeederFb
{
	RT_LABEL_FEEDER_FWD = 0,
	RT_LABEL_FEEDER_BWD,
	RT_LABEL_FEEDER_FB_MAX,
};

enum PosOfCylRtLabelFeederMountFb
{
	RT_LABEL_FEEDER_MOUNT_FWD = 0,
	RT_LABEL_FEEDER_MOUNT_BWD,
	RT_LABEL_FEEDER_MOUNT_FB_MAX,
};

enum PosOfCylRtLabelFeederLockFtFb
{
	RT_LABEL_FEEDER_LOCK_FT_FWD = 0,
	RT_LABEL_FEEDER_LOCK_FT_BWD,
	RT_LABEL_FEEDER_LOCK_FT_FB_MAX,
};

enum PosOfCylRtLabelFeederLockRrFb
{
	RT_LABEL_FEEDER_LOCK_RR_FWD = 0,
	RT_LABEL_FEEDER_LOCK_RR_BWD,
	RT_LABEL_FEEDER_LOCK_RR_FB_MAX,
};

enum PosOfCylRtLabelRecvUd
{
	RT_LABEL_RECV_UP = 0,
	RT_LABEL_RECV_DN,
	RT_LABEL_RECV_UD_MAX,
};

enum PosOfCylRtLabelRecvFb
{
	RT_LABEL_RECV_FWD = 0,
	RT_LABEL_RECV_BWD,
	RT_LABEL_RECV_FB_MAX,
};

enum PosOfCylRtLabelRecvEjectPinLtUd
{
	RT_LABEL_RECV_EJECT_PIN_LT_UP = 0,
	RT_LABEL_RECV_EJECT_PIN_LT_DN,
	RT_LABEL_RECV_EJECT_PIN_LT_UD_MAX,
};

enum PosOfCylRtLabelRecvEjectPinRtUd
{
	RT_LABEL_RECV_EJECT_PIN_RT_UP = 0,
	RT_LABEL_RECV_EJECT_PIN_RT_DN,
	RT_LABEL_RECV_EJECT_PIN_RT_UD_MAX,
};

enum PosOfCylPowerMeterOc
{
	POWER_METER_OPEN = 0,
	POWER_METER_CLOSE,
	POWER_METER_OC_MAX,
};

enum PosOfCylLabelQcViFb
{
	LABEL_QC_VI_FWD = 0,
	LABEL_QC_VI_BWD,
	LABEL_QC_VI_FB_MAX,
};

enum PosOfCylRtCobotLabelPkUd
{
	RT_COBOT_LABEL_PK_UP = 0,
	RT_COBOT_LABEL_PK_DN,
	RT_COBOT_LABEL_PK_UD_MAX,
};

enum PosOfCylRtCobotLabelPkTurnFb
{
	RT_COBOT_LABEL_PK_TURN_FWD = 0,
	RT_COBOT_LABEL_PK_TURN_BWD,
	RT_COBOT_LABEL_PK_TURN_FB_MAX,
};

enum PosOfCylLtMbbCstFb
{
	LT_MBB_CST_FWD = 0,
	LT_MBB_CST_BWD,
	LT_MBB_CST_FB_MAX,
};

enum PosOfCylRtMbbCstFb
{
	RT_MBB_CST_FWD = 0,
	RT_MBB_CST_BWD,
	RT_MBB_CST_FB_MAX,
};

enum PosOfcylMbbFoldPkLtAssistFb
{
	MBB_FOLD_PK_LT_ASSIST_FWD = 0,
	MBB_FOLD_PK_LT_ASSIST_BWD,
	MBB_FOLD_PK_LT_FB_ASSIST_MAX,
};

enum PosOfcylSealMbbClampUd
{
	SEAL_MBB_CLAMP_UP = 0,
	SEAL_MBB_CLAMP_DN,
	SEAL_MBB_CLAMP_UD_MAX,
};

enum PosOfcylSealMbbClampFb
{
	SEAL_MBB_CLAMP_FWD = 0,
	SEAL_MBB_CLAMP_BWD,
	SEAL_MBB_CLAMP_FB_MAX,
};

enum PosOfcylSealMbbClampOc
{
	SEAL_MBB_CLAMP_OPEN = 0,
	SEAL_MBB_CLAMP_CLOSE,
	SEAL_MBB_CLAMP_OC_MAX,
};

enum PosOfcylMbbShuttleClampUd
{
	MBB_SHUTTLE_CLAMP_UP = 0,
	MBB_SHUTTLE_CLAMP_DN,
	MBB_SHUTTLE_CLAMP_UD_MAX,
};